/**
 * Approval mirroring for Pi.
 *
 * Pi's approvals reach Herdr's UI but never the phone, and this file is the missing
 * link. The chain today is:
 *
 *   gentle-pi  --emits-->  pi-permission-system:permission-request  --X-->  nobody
 *
 * moshi-hook's own generated Pi extension (`moshi-hooks.ts`) already knows how to
 * build the `PermissionRequest` envelope and even documents the intent ("Pi owns the
 * approval prompt and decision. Moshi mirrors the waiting state"), but it never
 * registers a handler that calls it, and Pi has no `PermissionRequest` event of its
 * own — it exposes `ui_prompt_start` / `ui_prompt_end`.
 *
 * This is a separate file on purpose: `moshi-hooks.ts` is auto-generated by
 * `moshi-hook install` and would overwrite any patch made in place.
 *
 * Pillars, matching the generated extension's discipline:
 *   - a hook must never interrupt the user's turn: every failure is silent;
 *   - nothing is written to the daemon except the envelope it already parses;
 *   - no credential, path or prompt body is ever invented for an unknown payload.
 */

import type { ExtensionAPI, ExtensionContext } from "@earendil-works/pi-coding-agent";
import { spawnSync } from "node:child_process";
import { createConnection } from "node:net";
import { homedir } from "node:os";
import { join as pathJoin } from "node:path";

/**
 * Emitted by gentle-pi's guarded-command path
 * (`extensions/gentle-ai.ts`, `emitPermissionRequest`), with
 * `{ requestId, state, source, message, toolName }`.
 *
 * This is Pi's inter-extension event bus, not Pi's lifecycle hooks: it is read
 * through `pi.events.on`, which returns an unsubscribe function.
 */
const PERMISSION_EVENT = "pi-permission-system:permission-request";

const agentSource = "pi";
const agentDisplayName = "Pi";


interface TerminalContext {
  terminalKind: string;
  tmuxSession: string;
  tmuxWindow: string;
  tmuxPane: string;
  tmuxSocket: string;
  zellijSession: string;
  zellijPane: string;
  herdrSession: string;
  herdrPane: string;
  herdrWorkspaceId: string;
  herdrWorkspace: string;
  herdrTabId: string;
  herdrTab: string;
}

/**
 * Mirrors `internal/config.SocketPath` in moshi-hook. The `MOSHI_SOCKET_PATH`
 * override wins so a throwaway daemon can be targeted.
 */
function resolveSocketPath(): string {
  const override = process.env.MOSHI_SOCKET_PATH;
  if (override) return override;
  if (process.platform === "darwin") {
    return pathJoin(homedir(), "Library", "Application Support", "Moshi", "moshi-hook.sock");
  }
  if (process.platform === "win32") {
    return "\\\\.\\pipe\\moshi-hook";
  }
  if (process.env.XDG_RUNTIME_DIR) {
    return pathJoin(process.env.XDG_RUNTIME_DIR, "moshi-hook.sock");
  }
  return "/tmp/moshi-hook.sock";
}

/**
 * One JSON line per connection: dial, write, half-close, drain the ack so the
 * daemon does not log broken pipes. Every failure resolves silently.
 */
function sendEnvelope(envelope: Record<string, unknown>): void {
  try {
    const sock = createConnection({ path: resolveSocketPath() });
    sock.setNoDelay(true);
    sock.on("error", () => {
      try {
        sock.destroy();
      } catch {}
    });
    sock.once("connect", () => {
      sock.write(JSON.stringify(envelope) + "\n");
      sock.end();
    });
    sock.on("data", () => {});
  } catch {}
}

/**
 * @param {Record<string, unknown>} record
 * @param {string} key
 * @returns {string}
 */
function firstString(...values: unknown[]): string {
  for (const value of values) {
    if (typeof value === "string" && value.length > 0) return value;
  }
  return "";
}

function redact(value: unknown): string {
  let text = typeof value === "string" ? value : String(value ?? "");
  text = text.replace(/[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}/g, "<email>");
  text = text.replace(/\beyJ[\w-]{8,}\.[\w-]{8,}\.[\w-]{4,}\b/g, "<jwt>");
  text = text.replace(/\b(sk-[A-Za-z0-9_-]{6})[A-Za-z0-9_-]+/g, "$1<redacted>");
  text = text.replace(/\b(ya29\.)[A-Za-z0-9_-]+/g, "$1<redacted>");
  text = text.replace(/\b(1\/\/)[A-Za-z0-9_-]+/g, "$1<redacted>");
  text = text.replace(/\b(rt\.[\w.]{4})[A-Za-z0-9_-]+/g, "$1<redacted>");
  text = text.replace(/(?:key|token|secret|password|auth|cookie|bearer)\s*[:=]\s*([^\s;,&]+)/gi, "$1=<redacted>");
  return text;
}

function runForOutput(command: string, args: string[], timeout: number): string {
  try {
    const result = spawnSync(command, args, { encoding: "utf8", timeout, windowsHide: true });
    return typeof result.stdout === "string" ? result.stdout : "";
  } catch {
    return "";
  }
}

function tmuxSocketFromEnv(value: string | undefined): string {
  if (!value) return "";
  const idx = value.indexOf(",");
  return idx > 0 ? value.slice(0, idx) : "";
}

/**
 * Where the approval prompt is actually waiting, which is what lets the daemon
 * address the pane instead of only describing it.
 */
function resolveTerminalContext(): TerminalContext {
  const tmuxPane = process.env.TMUX_PANE ?? "";
  const tmuxSocket = tmuxSocketFromEnv(process.env.TMUX);
  let tmuxSession = "";
  let tmuxWindow = "";
  if (process.env.TMUX) {
    const args = ["display-message", "-p"];
    if (tmuxPane) args.push("-t", tmuxPane);
    args.push("#S\t#I");
    const output = runForOutput("tmux", args, 200).trim();
    if (output) {
      const parts = output.split("\t", 2);
      tmuxSession = parts[0] ?? "";
      tmuxWindow = parts[1] ?? "";
    }
  }
  const zellijSession = process.env.ZELLIJ_SESSION_NAME ?? "";
  const zellijPane = process.env.ZELLIJ_PANE_ID ?? "";
  const inHerdr = process.env.HERDR_ENV === "1";

  let terminalKind = "";
  if (tmuxSession) terminalKind = "tmux";
  else if (inHerdr) terminalKind = "herdr";
  else if (process.env.ZELLIJ || zellijSession || zellijPane) terminalKind = "zellij";

  return {
    terminalKind,
    tmuxSession,
    tmuxWindow,
    tmuxPane,
    tmuxSocket,
    zellijSession,
    zellijPane,
    herdrSession: inHerdr ? process.env.HERDR_SESSION ?? "" : "",
    herdrPane: inHerdr ? process.env.HERDR_PANE_ID ?? "" : "",
    herdrWorkspaceId: inHerdr ? process.env.HERDR_WORKSPACE_ID ?? "" : "",
    herdrWorkspace: "",
    herdrTabId: inHerdr ? process.env.HERDR_TAB_ID ?? "" : "",
    herdrTab: "",
  };
}

function projectNameFromCwd(cwd: string): string {
  if (!cwd) return "";
  const trimmed = cwd.replace(/[\/\\]+$/, "");
  const idx = Math.max(trimmed.lastIndexOf("/"), trimmed.lastIndexOf("\\"));
  return idx >= 0 ? trimmed.slice(idx + 1) : trimmed;
}

function newSessionID(): string {
  const buf = new Uint8Array(16);
  try {
    crypto.getRandomValues(buf);
  } catch {
    for (let i = 0; i < buf.length; i += 1) buf[i] = Math.floor(Math.random() * 256);
  }
  return Array.from(buf, (b) => b.toString(16).padStart(2, "0")).join("");
}

interface CachedSession {
  sessionId: string;
  transcriptPath: string;
  cwd: string;
  model: string;
  contextRemaining: number | undefined;
}

/** The parts of Pi's session that the envelope needs but the event bus does not carry. */
function emptySession(): CachedSession {
  return { sessionId: "", transcriptPath: "", cwd: "", model: "", contextRemaining: undefined };
}

function sessionIDFrom(ctx: Record<string, unknown>): string {
  const sessionManager = ctx.sessionManager as Record<string, unknown> | undefined;
  const getSessionId = sessionManager?.getSessionId;
  if (typeof getSessionId !== "function") return "";
  try {
    return String(getSessionId.call(sessionManager) ?? "");
  } catch {
    return "";
  }
}

function transcriptPathFrom(ctx: Record<string, unknown>): string {
  const sessionManager = ctx.sessionManager as Record<string, unknown> | undefined;
  const getSessionFile = sessionManager?.getSessionFile;
  if (typeof getSessionFile !== "function") return "";
  try {
    return String(getSessionFile.call(sessionManager) ?? "");
  } catch {
    return "";
  }
}

function modelLabel(model: unknown): string {
  if (!model || typeof model !== "object") return "";
  const obj = model as Record<string, unknown>;
  return firstString(obj.displayName, obj.display_name, obj.name, obj.id, obj.modelId);
}

/** Remaining context as a percentage, matching the generated extension's convention. */
function contextRemainingFrom(ctx: Record<string, unknown>): number | undefined {
  const getContextUsage = ctx.getContextUsage;
  if (typeof getContextUsage !== "function") return undefined;
  try {
    const usage = getContextUsage.call(ctx) as { percent?: unknown } | undefined;
    if (typeof usage?.percent !== "number" || !Number.isFinite(usage.percent)) return undefined;
    return Math.max(1, Math.min(100, Math.round(100 - usage.percent)));
  } catch {
    return undefined;
  }
}

export default function moshiApprovals(pi: ExtensionAPI): void {
  // Resolved per extension instance, not at module load: a reloaded extension must
  // pick up the terminal it is actually running in.
  const terminalContext = resolveTerminalContext();
  let session = emptySession();

  const remember = (_event: unknown, ctx: unknown): void => {
    try {
      const ctxObj = ctx && typeof ctx === "object" ? (ctx as Record<string, unknown>) : {};
      session = {
        sessionId: sessionIDFrom(ctxObj) || session.sessionId,
        transcriptPath: transcriptPathFrom(ctxObj) || session.transcriptPath,
        cwd: firstString(ctxObj.cwd, process.cwd()) || session.cwd,
        model: modelLabel(ctxObj.model) || session.model,
        contextRemaining: contextRemainingFrom(ctxObj),
      };
    } catch {
      // Remembering is best-effort; the envelope falls back to what it has.
    }
  };

  pi.on("session_start", remember);
  pi.on("before_agent_start", remember);
  pi.on("agent_start", remember);
  pi.on("session_shutdown", () => {
    // A closed session must not be reused by a later approval.
    session = emptySession();
  });

  /**
   * @param {string} eventName
   * @param {Record<string, unknown>} extra
   * @returns {Record<string, unknown>}
   */
  const envelopeFor = (eventName: string, extra: Record<string, unknown>): Record<string, unknown> => {
    const cwd = session.cwd || process.cwd();
    const envelope: Record<string, unknown> = {
      type: "session.update",
      source: agentSource,
      sessionId: session.sessionId || newSessionID(),
      eventName,
      cwd,
      projectName: terminalContext.tmuxSession || terminalContext.herdrSession || terminalContext.zellijSession || projectNameFromCwd(cwd),
      terminalKind: terminalContext.terminalKind,
      tmuxSession: terminalContext.tmuxSession,
      tmuxWindow: terminalContext.tmuxWindow,
      tmuxPane: terminalContext.tmuxPane,
      tmuxSocket: terminalContext.tmuxSocket,
      zellijSession: terminalContext.zellijSession,
      zellijPane: terminalContext.zellijPane,
      herdrSession: terminalContext.herdrSession,
      herdrPane: terminalContext.herdrPane,
      herdrWorkspaceId: terminalContext.herdrWorkspaceId,
      herdrWorkspace: terminalContext.herdrWorkspace,
      herdrTabId: terminalContext.herdrTabId,
      herdrTab: terminalContext.herdrTab,
      modelName: session.model,
      transcriptPath: session.transcriptPath,
      requestedAt: new Date().toISOString(),
      ...extra,
    };
    if (typeof session.contextRemaining === "number" && session.contextRemaining > 0) {
      envelope.contextRemaining = session.contextRemaining;
    }
    return envelope;
  };

  /**
   * @param {unknown} data
   */
  const onPermissionRequest = (data: unknown): void => {
    try {
      if (!data || typeof data !== "object" || Array.isArray(data)) return;
      const payload = data as Record<string, unknown>;
      const requestId = firstString(payload.requestId);
      const state = firstString(payload.state);
      const toolName = firstString(payload.toolName);
      // An unknown state is not guessed at: only the three the emitter documents
      // produce an envelope.
      if (!requestId || (state !== "waiting" && state !== "approved" && state !== "denied")) return;

      if (state === "waiting") {
        sendEnvelope(
          envelopeFor("PermissionRequest", {
            actionId: requestId,
            phase: "waitingForApproval",
            category: "approval_required",
            toolName,
            title: agentDisplayName + " needs approval",
            // Remote approval only lands when the daemon can re-find this prompt on
            // screen, which it does about one time in eight. The card never promises
            // more than that.
            subtitle: "Answer in terminal",
            message: redact(firstString(payload.message)).trim().replace(/\s+/g, " ").slice(0, 256),
          }),
        );
        return;
      }

      sendEnvelope(
        envelopeFor("PermissionResolved", {
          actionId: requestId,
          category: "session_started",
          toolName,
          title: agentDisplayName + " resumed",
          // The generated extension says only "Pi resumed"; naming the decision is
          // the one thing the phone cannot infer.
          message: toolName ? `${toolName} ${state}` : state,
        }),
      );
    } catch {
      // An approval hook must never interrupt the user's turn.
    }
  };

  pi.events.on(PERMISSION_EVENT, onPermissionRequest);
}
